pruebasubir/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static
from subir.views import login,registro
from django.conf.urls import url

from django.contrib.auth import views as auth_views



from django.urls import reverse_lazy
from django.contrib.auth.views import (
    login, logout, password_reset, password_reset_done, password_reset_confirm,
    password_reset_complete
)



urlpatterns = [
    path('indexex/', include('subir.urls')),
    path('usuario/', include('usuario.urls')),
    path('admin/', admin.site.urls),
    path('oauth/', include('social_django.urls', namespace='social')),
    

	url(r'^reset-password/$', password_reset, {'template_name': 'accounts/reset_password.html', 'post_reset_redirect': 'password_reset_done', 'email_template_name': 'accounts/reset_password_email.html'}, name='reset_password'),
    
    url(r'^reset-password/done/$', password_reset_done, {'template_name': 'accounts/reset_password_done.html'}, name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'template_name': 'accounts/reset_password_confirm.html', 'post_reset_redirect': 'password_reset_complete'}, name='password_reset_confirm'),
    url(r'^reset-password/complete/$', password_reset_complete,{'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

subir/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views



urlpatterns = [
    path('', views.index, name='index'),
    path('indexpk/<int:pk>', views.receta_detalle, name='receta_detalle'),
    path('registro/', views.registro, name='registro'),
    
    path('login/', views.login, name='login'),
    path('seccionveganos/', views.seccionveganos, name='seccionveganos'),
    
    
    path('subirrecetas/', views.subirrecetas_set, name='subirrecites'),
    path('perfil/', views.verperfil, name='verpefil'),
    path('categorias/',views.categorias,name='categorias'),
    path('ve_a_cocinar/',views.cocina,name='cocinar'),
    path('buscadoring/',views.buscadoring,name='buscadoring'),
    path('album/',views.album,name='album'),
    path('recuperar/',views.recuperar,name='recuperar'),
    path('done_recuperar/',views.done_recuperar,name='done_recuperar'),
    path('recuperacion_fallida/',views.fallida,name='recuperacion_fallada'),
    path('confirmar_recuperacion/',views.confirmacionrecuperar,name='confirmacion_recuperacion'),
    path('vista_receta/',views.vista_receta,name='vista_receta'),
    path('resultadosglobales/',views.resultadosglobales,name='resultadosglobales'),
    path('vista_perfil/',views.vista_perfil,name='vista_perfil'),
    path('fotoprueba/',views.fotoprueba,name='fotoprueba'),
    path('vistafotorecortada/',views.vistafotorecortada,name='vistafotorecortada')
    
   
]

usuario/urls.py
from django.conf.urls import url

from . import views
from django.urls import path

from django.contrib.auth import views as auth_views



from django.urls import reverse_lazy



from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

app_name = 'usuario'

urlpatterns = [


	path('', views.index,name='bienvenida'),
	
	path('login/', views.nevera_login),
	path('login/process/', views.login_process),
	path('logout/', views.nevera_logout),
    url(r'^users_existentes/$', views.users_existentes, name='users_existentes'),
    url(r'^correos_existentes/$', views.correos_existentes, name='correos_existentes'),
	path('register/', views.register),

	#para editar la cuenta(pass,name,username,ets)
	path('configuracion/', views.conf),

	path('profile/<username>/', views.profile,name='profile'),
	
	path('follow/', views.follow),
	path('seguirprueba/<username>/', views.seguirprueba),
	
	path('borrar/<tweet_id>/', views.borrar),

	path('buscar/', views.buscar),

	url('^(?P<method>(seguidores|siguiendo))/(?P<username>[a-zA-Z0-9\\_]+)/$', views.seguidores)

	



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

subir/forms.py
from .models import Recetas,pruebafoto2

from django.forms import ModelForm

from django import forms

class Prb1Form(ModelForm):
    class Meta:
        model = Recetas
        fields = '__all__'
        
        
class pruebafotoform(ModelForm):
    class Meta:
        model = pruebafoto2
        fields = '__all__'
        
class ContactForm(forms.Form):
    Asunto = forms.CharField(max_length=100)
    Nombre = forms.CharField(max_length=100, required=False)
    Correo = forms.EmailField()
    Contenido = forms.CharField(widget=forms.Textarea)          

subir/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.template import loader
from .forms import Prb1Form,ContactForm,pruebafotoform
from .models import *
from django.core.mail import EmailMessage
from django.core.mail import send_mail
from django.core.paginator import Paginator , EmptyPage , PageNotAnInteger
from django.template import loader
from django.contrib.auth.models import Group
from django.db.models import Q
from django.db.models import Count
from usuario.models import Profile2 , Follow
from datetime import date
from django.contrib.auth.models import User
# Create your views here.

def index(request):
    if request.user.is_authenticated:
        u = request.user
        p = get_object_or_404(Profile2, user = u)
        Rec=RecetasAdministracion.objects.all()

        hoy = date.today()        
        filtro_fecha = RecetasAdministracion.objects.filter(fecha__lte = hoy).order_by('-fecha')
        cantidad_usuarios = User.objects.annotate(cantidad_us = Count('username'))
        cant = len(cantidad_usuarios)
        usuarios_ff = Follow.objects.filter(followed__lte = cant).order_by('-followed')[:3]
        #usuarios_recientes =  RecetasAdministracion.objects.annotate(num_seguidores = Count('ingredientesadministracion__nombre',filter=Q(ingredientesadministracion__nombre__in = texto_buscar))).order_by('-num_ingredientes')[:3]
        
        fofo = Follow.objects.all().values('followed')
        
        print('FFOFOOFOF',fofo)
                
        context={'Rec':Rec,'filtro_fecha': filtro_fecha,'usuarios_ff' : usuarios_ff ,'logueado' : request.user, 'avatares':p.imagen} 
        return render(request,'subir/indexex.html',context)
    else:
        return redirect('/usuario/login')
        
def verperfil(request):
    return render(request,'subir/perfil_usuario_logeado.html')

def categorias(request):
    if request.user.is_authenticated:
        u = request.user
        p = get_object_or_404(Profile2, user = u)
        context={'logueado':request.user,'avatares':p.imagen}
        return render(request,'subir/categorias.html',context)
    else:
        return redirect('/usuario/login')

def cocina(request):
    if request.user.is_authenticated:
        u = request.user
        p = get_object_or_404(Profile2, user = u)
        per=RecetasAdministracion.objects.all()
        context={'per':per,'logueado':request.user,'avatares':p.imagen} 
        return render(request,'subir/ve a cocinar2.html',context)
    else:
        return redirect('/usuario/login')

def album(request):
    if request.user.is_authenticated:
        u = request.user
        p = get_object_or_404(Profile2, user = u)
        context={'logueado':request.user,'avatares':p.imagen} 
        return render(request,'subir/album.html',context)
    else:
        return redirect('/usuario/login')
    """
    ('veganos','veganos'),
    ('comidas rapidas','comidas rapidas'),
    ('tercera','tercera edad'),
    ('niños','niños'),
    ('desayuno','desayuno'),
    ('almuerzo','almuerzo'),
    ('cena','cena')
    """
def seccionveganos(request):
    if request.user.is_authenticated:
        u = request.user
        p = get_object_or_404(Profile2, user = u)
        albunes=request.POST['inputalbum']
        tt = RecetasAdministracion.objects.filter(album=albunes)
        return render(request,'subir/seccionveganos.html',{'tt':tt,'logueado':request.user,'avatares':p.imagen})
    else:
        return redirect('/usuario/login')
            

def recuperar(request):
    return render(request,'subir/recuperar_contrasenia2.html')

def done_recuperar(request):
    return render(request,'subir/done_recuperar2.html')

def fallida(request):
    return render(request,'subir/recuperacion_fallada.html')

def confirmacionrecuperar(request):
    return render(request,'subir/confirmacion_recuperacion.html')

def registro(request):
    return render(request,'subir/REGISTRO.html')

def login(request):
    return render(request,'subir/index_login.html')

def vista_receta(request):
    if request.user.is_authenticated:
        u = request.user
        p = get_object_or_404(Profile2, user = u)
        context={'logueado':request.user,'avatares':p.imagen} 
        return render(request,'subir/vista_receta.html',context)
        def __str__(self):
            return "%s (%s)" % (
                self.nombre,
                ", ".join(ingrediente.nombre for ingrediente in self.Ingredientes.all()),
        )
    else:
        return redirect('/usuario/login')
    


def resultadosglobales(request):
    if request.user.is_authenticated:
        u = request.user
        p = get_object_or_404(Profile2, user = u)
        buscar=request.POST['buscador'].lower()
        pr=RecetasAdministracion.objects.filter(nombre__icontains=buscar)
        context={'pr':pr,'avatares':p.imagen,'logueado' : request.user}
        return render(request,'subir/resultadosglobales.html',context)
    else:
        return redirect('/usuario/login')
    
        
def receta_detalle(request,pk):
    if request.user.is_authenticated:
        u = request.user
        p = get_object_or_404(Profile2, user = u)
        Rec=RecetasAdministracion.objects.all()
        receta=get_object_or_404(RecetasAdministracion,pk=pk)
        context={'logueado':request.user,'receta':receta,'avatares':p.imagen} 
        return render(request,'subir/vista_receta.html',context)
    else:
        return redirect('/usuario/login')
    

def vista_perfil(request):
    if request.user.is_authenticated:
        context={'logueado':request.user} 
        return render(request,'subir/perfil_usuarios.html',context)
    else:
        return redirect('/usuario/login')

def subirrecetas_set(request):
    if request.user.is_authenticated:
        u = request.user
        p = get_object_or_404(Profile2, user = u)
        if request.method == 'POST':
            form_class = ContactForm
            form = Prb1Form(request.POST, request.FILES)
            form2 = ContactForm(request.POST or None)
            if form2.is_valid():
                data = form2.cleaned_data
                entrada = form.save(commit=True)
                send_mail(
                    data['Asunto'],#asunto del correo
                    data['Contenido'],#Nombre de quien lo envia
                    [data['Correo']], #Correo de quien lo envia
                    ['tunevera.official@gmail.com'],#para quien va el correo 
                fail_silently=False)
                entrada.save()
                return redirect('/indexex/')
        else:
            form = Prb1Form()
            form2 = ContactForm()


        template = loader.get_template('subir/subirrecetas.html')

        context = {
            'form' : form
            }

        return render(request, 'subir/subirrecetas.html', {'form':form, 'form2':form2,'logueado':request.user,'idlogueado':request.user.id,'avatares':p.imagen})
    else:
        return redirect('/usuario/login')

def fotoprueba(request):
    
    if request.method == 'POST':
        form = pruebafotoform(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('../vistafotorecortada/')
    else:
        form = pruebafotoform()
        
    return render(request, 'subir/pruebafoto.html',{'form':form})
    
def buscadoring(request):
    if request.POST['texto_buscar']=="":
        return render(request,'subir/interrogantes.html')
    if request.method == "POST":
        texto_buscar = request.POST['texto_buscar'].split(',')
    else:
        texto_buscar = ''
    
    
    queryset  =IngredientesAdministracion.objects.filter(nombre =texto_buscar) 
    

    ll=RecetasAdministracion.objects.filter(ingredientesadministracion__nombre__in = texto_buscar).distinct()
    
    llcant=len(ll)
    print(llcant)
    
    print(queryset)
    

    
    if llcant == 1:
        xxx = RecetasAdministracion.objects.annotate(num_ingredientes = Count('ingredientesadministracion__nombre',filter=Q(ingredientesadministracion__nombre__in = texto_buscar))).order_by('-num_ingredientes')[:1]
        context = {'xxx': xxx}
        return render(request,'subir/prueba1.html',context)
    
    if llcant == 2:
        xxx = RecetasAdministracion.objects.annotate(num_ingredientes = Count('ingredientesadministracion__nombre',filter=Q(ingredientesadministracion__nombre__in = texto_buscar))).order_by('-num_ingredientes')[:2]
        context = {'xxx': xxx}
        return render(request,'subir/prueba2.html',context)
    
    if llcant >=3:
        xxx = RecetasAdministracion.objects.annotate(num_ingredientes = Count('ingredientesadministracion__nombre',filter=Q(ingredientesadministracion__nombre__in = texto_buscar))).order_by('-num_ingredientes')[:3]
        context = {'xxx': xxx}
        return render(request,'subir/prueba.html',context)
        
        


def vistafotorecortada(request):
    tt=pruebafoto2.objects.all()
    context={'tt':tt} 
    return render(request, 'subir/vistafotorecortada.html',{'tt':tt})

subir/templates/accounts/reset_password.html
{% extends 'subir/base_recuperar.html' %}



{% load static %}
           
           {% block titulo %}Recuperar contraseña {% endblock %}
            
 {% block contenidorecuperar %}
             
        
            
            <h4 class="display-4 text-muted">Recuperar contraseña</h4>
            
            <p>Ingresa tu correo electronico para configurar una nueva contraseña</p>
            <form method="post">
               
               {% csrf_token %}
                <div class="form-group form-inline" :class="{'has-success':validacion,'has-danger':error}">
      
                         
                        <label class="mr-4">Correo electronico:</label> 
                        
                        <input @keyup="validarcorreo" type="email" id="validar" class="form-control" pattern="^[a-z0-9]+(\.[_a-z0-9]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,15})$" :class="{'form-control-success':validacion,'form-control-danger':error}" required id={{ form.email }}

                        
                        
                       

                </div>
               
         
                <hr class="hidden-xs-down">
                <button type="submit" class="btn btn-warning hidden-sm-down">Recuperar contraseña</button>   
                <button type="submit" class="btn btn-warning btn-block hidden-md-up">Recuperar contraseña</button>   
           
           </form> 
           
           
<script>
new Vue({
    el:'#contenedor',
    data:{
        validacion:false,
        error:false
    },
    
    methods:{
        
        validarcorreo(){
    
            var patron= $('#validar').attr('pattern')
             var val = $('#validar').val()
             
             // el RegExp sirve para crear una nueva expresion de patrones de string para llevar a cumplir ciertos parametros en un campo
             
                var pat = new RegExp(patron)
                // la funcion exec, sirve para decirle que me ejecute esa expresion de caracteres y parametros, para que me cumpla en el campo solicitado
            if(val==""){
                   this.validacion=false
                    this.error=false
            }    
                
                
            else if(!pat.exec(val)){
                    this.validacion=false
                    this.error=true
                    
                    
                }
            
            else{
                
                this.error=false
                this.validacion=true
                
               
            }
            
                
          
            
          
                 
                     
        }
    }
    
    
})    
    
</script>
   
{% endblock %}

subir/templates/accounts/reset_password_complete.html
{% extends 'subir/base_recuperar.html' %}

{% load static %}




           
{% block contenidorecuperar %}
             
          
            
         
    <h1>Password reset complete</h1>
    <a class="btn btn-warning" href="{% url 'usuario:bienvenida' %}">Login</a>
            
   
{% endblock %}

subir/templates/accounts/reset_password_confirm.html
{% extends 'subir/base_recuperar.html' %}
            
{% load static %}
             
{% block title %}
    Confirmacion Recuperacion
{% endblock %}           
             
             {% block contenidorecuperar %}
             
            <h4 class="display-4 text-muted col-sm-10 px-0">Ingrese una nueva contraseña</h4>
                 
            <p class="text-justify col-sm-10 px-0">
              por favor ingrese una nueva contraseña, nosotros verificaremos que este correcta
            
            </p>
            
            
            <form method="post">
                   {% csrf_token %}
                    <div class="form-group row px-3">
                    <div class="col-auto align-self-center" style="margin-right:58px;">
                        <strong class="">Nueva contraseña</strong> 
                    </div>
                    <div class="col-auto">

                    <div class="form-group"  :class="{'has-success':coinciden,'has-danger':nocoinciden}">
                        <input type="password" @keyup="validacionclave" class="clave form-control" :class="{'form-control-success':coinciden,'form-control-danger':nocoinciden}" pattern="^(?=\w*\d)^([A-Za-z])\S{8,16}$" maxlength="30" required id={{form.new_password1}}
                    </div>
                   </div>       

                    <div class="w-100 my-2"></div>            

                    <div class="col-auto align-self-center" style="margin-right:30px;">
                        <strong class="">Confirmar contraseña</strong> 
                    </div>
                    <div class="col-auto">

                    <div class="form-group" :class="{'has-success':coinciden,'has-danger':nocoinciden}">
                        <input id="confirmacionclave" type="password" @keyup="validacionclave" class="clave form-control" :class="{'form-control-success':coinciden,'form-control-danger':nocoinciden}"  id={{form.new_password2}}
                        <span class="form-control-feedback" v-show="coinciden">Las contraseñas coinciden</span>
                        <span class="form-control-feedback" v-show="nocoinciden">Las contraseñas no coinciden</span>
           
                    </div>
                   </div>

                </div>

                <hr class="hidden-xs-down">
                <button type="submit" class="btn btn-warning hidden-sm-down">Cambiar contraseña</button>   
                <button type="submit" class="btn btn-warning btn-block hidden-md-up">Cambiar contraseña</button>   

             </form>
             
             
            <script>
new Vue({
    el:'#contenedor',
    data:{
        
        validacion:false,
        error:false,
        validacion2:false,
        error2:false,
        validacion3:false,
        error3:false,
        coinciden:false,
        nocoinciden:false

    },
    methods:{     
        validacionclave(){
            

                
             var val1 = $('.clave').val()
             var val2 = $('#confirmacionclave').val()

          
             
//nu
                    
            if(val1==val2){
                
                if(val1!=""){
                    this.coinciden=true
                    this.nocoinciden=false
                }
            }
            
                        
            else if(val1=="" || val2==""){
                this.coinciden=false
                this.nocoinciden=false
                
            }
            
            
            else if(val1!=val2){
                this.coinciden=false
                this.nocoinciden=true
            }


    } 
        
    }
    
    
})    
    
</script>    
         
             
          {% endblock %}

subir/templates/accounts/reset_password_done.html
{% extends 'subir/base_recuperar.html' %}


{% load static %}
             
            
{% block contenidorecuperar %}
             
    <h4 class="display-4 text-muted col-sm-10 px-0">Recuperar contraseña</h4>
                 
    <p class="text-justify col-sm-10 px-0">Le enviamos por correo electrónico instrucciones para configurar su contraseña, si existe una cuenta con el correo electrónico que ingresó, debe recibirla en breve.
    Si no recibe un correo electrónico, asegúrese de haber ingresado la dirección con la que se registró y revise su carpeta de correo no deseado.</p>
             
{% endblock %}
      
        
        
      

            

subir/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}

{% blocktrans %}
está recibiendo este correo por que solicitó un restablecimiento de contraseña para su cuenta de usuario en {{ site_name }}.{% endblocktrans %}


{% trans "por favor vaya a la siguiente página y elija una nueva contraseña:" %}


{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}

{% trans "su nombre de usuario, en caso de que lo haya olvidado:" %} {{ user.get_username }}

{% trans "Gracias por visitarnos!" %}

{% blocktrans %} {{ site_name }} El equipo de Tu nevera{% endblocktrans %}

{% endautoescape %}